# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10worker_rpc.proto\x12\x04\x63riu\"\"\n\x0bInitRequest\x12\x13\n\x0b\x63onfig_path\x18\x01 \x01(\t\"0\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\nRunRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x1d\n\x0bRunResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x11\n\x0fShutdownRequest\"#\n\x10ShutdownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa3\x01\n\x0b\x43RIUService\x12-\n\x04Init\x12\x11.criu.InitRequest\x1a\x12.criu.InitResponse\x12*\n\x03Run\x12\x10.criu.RunRequest\x1a\x11.criu.RunResponse\x12\x39\n\x08Shutdown\x12\x15.criu.ShutdownRequest\x1a\x16.criu.ShutdownResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITREQUEST._serialized_start=26
  _INITREQUEST._serialized_end=60
  _INITRESPONSE._serialized_start=62
  _INITRESPONSE._serialized_end=110
  _RUNREQUEST._serialized_start=112
  _RUNREQUEST._serialized_end=141
  _RUNRESPONSE._serialized_start=143
  _RUNRESPONSE._serialized_end=172
  _SHUTDOWNREQUEST._serialized_start=174
  _SHUTDOWNREQUEST._serialized_end=191
  _SHUTDOWNRESPONSE._serialized_start=193
  _SHUTDOWNRESPONSE._serialized_end=228
  _CRIUSERVICE._serialized_start=231
  _CRIUSERVICE._serialized_end=394
# @@protoc_insertion_point(module_scope)
