# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import worker_rpc_pb2 as worker__rpc__pb2


class CRIUServiceStub(object):
    """CRIU RPC 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/criu.CRIUService/Init',
                request_serializer=worker__rpc__pb2.InitRequest.SerializeToString,
                response_deserializer=worker__rpc__pb2.InitResponse.FromString,
                )
        self.Run = channel.unary_unary(
                '/criu.CRIUService/Run',
                request_serializer=worker__rpc__pb2.RunRequest.SerializeToString,
                response_deserializer=worker__rpc__pb2.RunResponse.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/criu.CRIUService/Shutdown',
                request_serializer=worker__rpc__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=worker__rpc__pb2.ShutdownResponse.FromString,
                )


class CRIUServiceServicer(object):
    """CRIU RPC 服务定义
    """

    def Init(self, request, context):
        """初始化
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """运行任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """关闭
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CRIUServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=worker__rpc__pb2.InitRequest.FromString,
                    response_serializer=worker__rpc__pb2.InitResponse.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=worker__rpc__pb2.RunRequest.FromString,
                    response_serializer=worker__rpc__pb2.RunResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=worker__rpc__pb2.ShutdownRequest.FromString,
                    response_serializer=worker__rpc__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'criu.CRIUService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CRIUService(object):
    """CRIU RPC 服务定义
    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/criu.CRIUService/Init',
            worker__rpc__pb2.InitRequest.SerializeToString,
            worker__rpc__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/criu.CRIUService/Run',
            worker__rpc__pb2.RunRequest.SerializeToString,
            worker__rpc__pb2.RunResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/criu.CRIUService/Shutdown',
            worker__rpc__pb2.ShutdownRequest.SerializeToString,
            worker__rpc__pb2.ShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
