# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import storage_pb2 as storage__pb2


class StorageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModelAsync = channel.unary_unary(
                '/storage.Storage/LoadModelAsync',
                request_serializer=storage__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=storage__pb2.LoadModelResponse.FromString,
                )
        self.ConfirmModel = channel.unary_unary(
                '/storage.Storage/ConfirmModel',
                request_serializer=storage__pb2.ConfirmModelRequest.SerializeToString,
                response_deserializer=storage__pb2.ConfirmModelResponse.FromString,
                )
        self.UnloadModel = channel.unary_unary(
                '/storage.Storage/UnloadModel',
                request_serializer=storage__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=storage__pb2.UnloadModelResponse.FromString,
                )
        self.ClearMem = channel.unary_unary(
                '/storage.Storage/ClearMem',
                request_serializer=storage__pb2.ClearMemRequest.SerializeToString,
                response_deserializer=storage__pb2.ClearMemResponse.FromString,
                )
        self.RegisterModel = channel.unary_unary(
                '/storage.Storage/RegisterModel',
                request_serializer=storage__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=storage__pb2.RegisterModelResponse.FromString,
                )
        self.GetServerConfig = channel.unary_unary(
                '/storage.Storage/GetServerConfig',
                request_serializer=storage__pb2.GetServerConfigRequest.SerializeToString,
                response_deserializer=storage__pb2.GetServerConfigResponse.FromString,
                )
        self.GetPoolHandle = channel.unary_unary(
                '/storage.Storage/GetPoolHandle',
                request_serializer=storage__pb2.GetPoolHandleRequest.SerializeToString,
                response_deserializer=storage__pb2.GetPoolHandleResponse.FromString,
                )
        self.GetAvailableBlocksOnGPU = channel.unary_unary(
                '/storage.Storage/GetAvailableBlocksOnGPU',
                request_serializer=storage__pb2.GetAvailableBlocksOnGPURequest.SerializeToString,
                response_deserializer=storage__pb2.GetAvailableBlocksOnGPUResponse.FromString,
                )
        self.AllocateBlocksOnGPU = channel.unary_unary(
                '/storage.Storage/AllocateBlocksOnGPU',
                request_serializer=storage__pb2.AllocateBlocksOnGPURequest.SerializeToString,
                response_deserializer=storage__pb2.AllocateBlocksOnGPUResponse.FromString,
                )
        self.RestoreCRIUEngine = channel.unary_unary(
                '/storage.Storage/RestoreCRIUEngine',
                request_serializer=storage__pb2.RestoreCRIUEngineRequest.SerializeToString,
                response_deserializer=storage__pb2.RestoreCRIUEngineResponse.FromString,
                )
        self.ToLoadSize = channel.unary_unary(
                '/storage.Storage/ToLoadSize',
                request_serializer=storage__pb2.ToLoadSizeRequest.SerializeToString,
                response_deserializer=storage__pb2.ToLoadSizeResponse.FromString,
                )
        self.ToLoadSizes = channel.unary_unary(
                '/storage.Storage/ToLoadSizes',
                request_serializer=storage__pb2.ToLoadSizesRequest.SerializeToString,
                response_deserializer=storage__pb2.ToLoadSizesResponse.FromString,
                )


class StorageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModelAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearMem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoolHandle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableBlocksOnGPU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateBlocksOnGPU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreCRIUEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToLoadSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToLoadSizes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModelAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModelAsync,
                    request_deserializer=storage__pb2.LoadModelRequest.FromString,
                    response_serializer=storage__pb2.LoadModelResponse.SerializeToString,
            ),
            'ConfirmModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmModel,
                    request_deserializer=storage__pb2.ConfirmModelRequest.FromString,
                    response_serializer=storage__pb2.ConfirmModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=storage__pb2.UnloadModelRequest.FromString,
                    response_serializer=storage__pb2.UnloadModelResponse.SerializeToString,
            ),
            'ClearMem': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearMem,
                    request_deserializer=storage__pb2.ClearMemRequest.FromString,
                    response_serializer=storage__pb2.ClearMemResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=storage__pb2.RegisterModelRequest.FromString,
                    response_serializer=storage__pb2.RegisterModelResponse.SerializeToString,
            ),
            'GetServerConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerConfig,
                    request_deserializer=storage__pb2.GetServerConfigRequest.FromString,
                    response_serializer=storage__pb2.GetServerConfigResponse.SerializeToString,
            ),
            'GetPoolHandle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolHandle,
                    request_deserializer=storage__pb2.GetPoolHandleRequest.FromString,
                    response_serializer=storage__pb2.GetPoolHandleResponse.SerializeToString,
            ),
            'GetAvailableBlocksOnGPU': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableBlocksOnGPU,
                    request_deserializer=storage__pb2.GetAvailableBlocksOnGPURequest.FromString,
                    response_serializer=storage__pb2.GetAvailableBlocksOnGPUResponse.SerializeToString,
            ),
            'AllocateBlocksOnGPU': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateBlocksOnGPU,
                    request_deserializer=storage__pb2.AllocateBlocksOnGPURequest.FromString,
                    response_serializer=storage__pb2.AllocateBlocksOnGPUResponse.SerializeToString,
            ),
            'RestoreCRIUEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreCRIUEngine,
                    request_deserializer=storage__pb2.RestoreCRIUEngineRequest.FromString,
                    response_serializer=storage__pb2.RestoreCRIUEngineResponse.SerializeToString,
            ),
            'ToLoadSize': grpc.unary_unary_rpc_method_handler(
                    servicer.ToLoadSize,
                    request_deserializer=storage__pb2.ToLoadSizeRequest.FromString,
                    response_serializer=storage__pb2.ToLoadSizeResponse.SerializeToString,
            ),
            'ToLoadSizes': grpc.unary_unary_rpc_method_handler(
                    servicer.ToLoadSizes,
                    request_deserializer=storage__pb2.ToLoadSizesRequest.FromString,
                    response_serializer=storage__pb2.ToLoadSizesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.Storage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Storage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModelAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/LoadModelAsync',
            storage__pb2.LoadModelRequest.SerializeToString,
            storage__pb2.LoadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/ConfirmModel',
            storage__pb2.ConfirmModelRequest.SerializeToString,
            storage__pb2.ConfirmModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/UnloadModel',
            storage__pb2.UnloadModelRequest.SerializeToString,
            storage__pb2.UnloadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearMem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/ClearMem',
            storage__pb2.ClearMemRequest.SerializeToString,
            storage__pb2.ClearMemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/RegisterModel',
            storage__pb2.RegisterModelRequest.SerializeToString,
            storage__pb2.RegisterModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/GetServerConfig',
            storage__pb2.GetServerConfigRequest.SerializeToString,
            storage__pb2.GetServerConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPoolHandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/GetPoolHandle',
            storage__pb2.GetPoolHandleRequest.SerializeToString,
            storage__pb2.GetPoolHandleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableBlocksOnGPU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/GetAvailableBlocksOnGPU',
            storage__pb2.GetAvailableBlocksOnGPURequest.SerializeToString,
            storage__pb2.GetAvailableBlocksOnGPUResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AllocateBlocksOnGPU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/AllocateBlocksOnGPU',
            storage__pb2.AllocateBlocksOnGPURequest.SerializeToString,
            storage__pb2.AllocateBlocksOnGPUResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestoreCRIUEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/RestoreCRIUEngine',
            storage__pb2.RestoreCRIUEngineRequest.SerializeToString,
            storage__pb2.RestoreCRIUEngineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToLoadSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/ToLoadSize',
            storage__pb2.ToLoadSizeRequest.SerializeToString,
            storage__pb2.ToLoadSizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToLoadSizes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storage.Storage/ToLoadSizes',
            storage__pb2.ToLoadSizesRequest.SerializeToString,
            storage__pb2.ToLoadSizesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
